#!/bin/bash
INPUT_PATH="$1"
OUTPUT_PATH="bin/${INPUT_PATH}"
OUTPUT_PATH="${OUTPUT_PATH%.*}"
OUTPUT_DIR="$(dirname "${OUTPUT_PATH}")"

mkdir -p "${OUTPUT_DIR}"
time g++ -Wno-narrowing --short-enums -fdiagnostics-color=always -std=c++17 -O2 -Isrc "${INPUT_PATH}" \
    -lpthread -lupscaledb -lstdc++fs -lz -lwebsockets -lcurl -ltbb \
    -o "${OUTPUT_PATH}" && echo && ./${OUTPUT_PATH}
exit $?
