#!/bin/bash
DEBUG=false

INPUT_PATH="$1"
OUTPUT_PATH="bin/${INPUT_PATH}"
OUTPUT_PATH="${OUTPUT_PATH%.*}"
OUTPUT_DIR="$(dirname "${OUTPUT_PATH}")"

if [ "${DEBUG}" = true ] ; then
    EXECUTION_PRECOMMAND="valgrind"
else
    EXECUTION_PRECOMMAND=""
fi

if [ "${DEBUG}" = true ] ; then
    OPTIONS="${OPTIONS} -g -O0"
else
    OPTIONS="${OPTIONS} -O3"
fi

mkdir -p "${OUTPUT_DIR}"
time g++ ${OPTIONS} --short-enums -fdiagnostics-color=always -std=c++17 -Isrc "${INPUT_PATH}" \
    -Wno-write-strings  -Wno-narrowing -Wno-trigraphs \
    -lpthread -lupscaledb -lstdc++fs -lz -lwebsockets -lcurl -ltbb -lncursesw \
    -o "${OUTPUT_PATH}" && echo && time ${EXECUTION_PRECOMMAND} ./${OUTPUT_PATH}
exit $?
